keywords = [
    "function",
    "local",
    "true",
    "false",

    "if",
    "then",
    "else",

    "while",
    "for",
    "in",
    "break",
    "do",
    "goto",

    "and",
    "or",

    "return",
    "end",
]

literals = [
    "Number",
    "Str",
]

tokens = [
    "Error",
    "Ident",
    "Shebang",
]

trivia = [
    "Comment",
    "Whitespace",
]

[punct]
"==" = "EqEq"
"~=" = "NotEq"

"=" = "Eq"

"(" = "LParen"
")" = "RParen"
"{" = "LBrace"
"}" = "RBrace"
"[" = "LBracket"
"]" = "RBracket"

"," = "Comma"
"." = "Dot"
";" = "Semicolon"
":" = "Colon"

"+" = "Plus"
"-" = "Minus"
"*" = "Asterisk"
"/" = "Slash"

"!" = "Bang"
