keywords = [
    "function",
    "local",
    "true",
    "false",

    "if",
    "then",
    "else",
    "elseif",

    "while",
    "for",
    "in",
    "break",
    "do",
    "goto",

    "and",
    "or",
    "not",

    "return",
    "end",

    "repeat",
    "until",

    "nil",
]

literals = [
    "Number",
    "Str",
]

tokens = [
    "Error",
    "Ident",
    "Shebang",
]

trivia = [
    "Comment",
    "Whitespace",
]

[punct]
"==" = "EqEq"
"~=" = "NotEq"

">" = "Gt"
">=" = "GtEq"
"<" = "Lt"
"<=" = "LtEq"

"=" = "Eq"

"(" = "LParen"
")" = "RParen"
"{" = "LBrace"
"}" = "RBrace"
"[" = "LBracket"
"]" = "RBracket"

"," = "Comma"
"." = "Dot"
";" = "Semicolon"
":" = "Colon"

"+" = "Plus"
"-" = "Minus"
"*" = "Asterisk"
"/" = "Slash"

# not for luajit
"%" = "Modulo"
"^" = "Caret"

# table length operator
"#" = "Hash"

"!" = "Bang"

".." = "DoubleDot"
"..." = "TripleDot"
